spring:
  datasource:
    url: jdbc:postgresql://localhost:62222/digital_chief_check_library
    username: postgres
    password: test_password
    driver-class-name: org.postgresql.Driver
    hikari:
      schema: public